CREATE TABLE public.applications (
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  city text,
  country text,
  phone text,
  ieltsScore text,
  satScore text,
  schoolName text,
  grade text,
  gpa text,
  parentPhone text,
  parentEmail text,
  firstName text,
  fieldsOfInterest ARRAY,
  researchInterest text,
  promoCode text,
  extracurriculars text,
  createdBy uuid NOT NULL DEFAULT auth.uid() UNIQUE,
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  lastName text,
  parentFirstName text,
  parentLastName text,
  CONSTRAINT applications_pkey PRIMARY KEY (id, createdBy)
);
